name: "Create connector test environment using KinD"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - name: setup Helm
        uses: azure/setup-helm@v1
      - uses: actions/checkout@v2
        name: checkout code
      - uses: engineerd/setup-kind@v0.4.0
        name: setup kind
        with:
            version: "v0.7.0"
      - name: Testing
        run: |
          echo "--\nk8s configuration after install\n--\n"
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
          cd charts
          echo "--\nSetting up & installing the test helm chart\n--\n"
          helm dep update egeria-database-connector-test
          helm install --wait test egeria-database-connector-test
          echo "--\nChecking all is running ok\n--\n"
          kubectl get pods
